services:
  - type: web
    name: finger-dental-manager
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
